import { useState, useEffect } from 'react';
import { Calendar, Trash2, ChevronDown, ChevronUp, Filter, FileDown } from 'lucide-react';
import { toast } from 'react-toastify';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import api from '../api.js';

function formatMoney(n) {
  return Number(n || 0).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function escapeHtml(value = '') {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function buildInventoryReportHtml(inventory) {
  const itemsRows = (inventory.items || [])
    .map((item, idx) => `
      <tr>
        <td>${idx + 1}</td>
        <td class="name">${escapeHtml(item.item_name)}</td>
        <td>${formatMoney(item.try_amount)}</td>
        <td>${formatMoney(item.usd_amount)}</td>
        <td class="note">${escapeHtml(item.notes || '-')}</td>
      </tr>
    `)
    .join('');

  const profitClass = Number(inventory.profit || 0) >= 0 ? 'profit-positive' : 'profit-negative';

  return `
    <div class="report">
      <style>
        .report {
          direction: rtl;
          font-family: Tahoma, Arial, sans-serif;
          color: #0f172a;
          background: linear-gradient(145deg, #f8fafc, #eef2f7);
          border: 1px solid #e2e8f0;
          border-radius: 18px;
          padding: 28px;
        }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 12px;
          margin-bottom: 16px;
        }
        .title {
          margin: 0;
          font-size: 30px;
          font-weight: 800;
          color: #065f46;
        }
        .sub {
          margin: 6px 0 0 0;
          color: #475569;
          font-size: 14px;
        }
        .badge {
          background: #d1fae5;
          color: #065f46;
          padding: 10px 16px;
          border-radius: 999px;
          font-weight: 700;
          font-size: 14px;
          border: 1px solid #a7f3d0;
        }
        .summary {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 12px;
          margin: 14px 0 20px 0;
        }
        .card {
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          padding: 12px;
        }
        .card .label {
          color: #64748b;
          font-size: 12px;
          margin-bottom: 4px;
        }
        .card .value {
          font-size: 20px;
          font-weight: 700;
        }
        .profit-positive { color: #15803d; }
        .profit-negative { color: #dc2626; }
        .table-wrap {
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 12px;
          overflow: hidden;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          font-size: 13px;
        }
        thead tr {
          background: #065f46;
          color: white;
        }
        th, td {
          padding: 10px 8px;
          border-bottom: 1px solid #e2e8f0;
          text-align: center;
          vertical-align: top;
        }
        tbody tr:nth-child(even) {
          background: #f8fafc;
        }
        td.name, td.note {
          text-align: right;
          word-break: break-word;
        }
        .footer {
          margin-top: 14px;
          color: #64748b;
          font-size: 12px;
          text-align: center;
        }
      </style>

      <div class="header">
        <div>
          <h1 class="title">تقرير الجرد اليومي</h1>
          <p class="sub">JRD Inventory Report</p>
        </div>
        <div class="badge">${escapeHtml(inventory.date)}</div>
      </div>

      <div class="summary">
        <div class="card">
          <div class="label">سعر الصرف</div>
          <div class="value">${formatMoney(inventory.exchange_rate)}</div>
        </div>
        <div class="card">
          <div class="label">إجمالي الجرد</div>
          <div class="value">$${formatMoney(inventory.total_converted_usd)}</div>
        </div>
        <div class="card">
          <div class="label">الربح</div>
          <div class="value ${profitClass}">$${formatMoney(inventory.profit)}</div>
        </div>
      </div>

      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>البند</th>
              <th>TRY ₺</th>
              <th>USD $</th>
              <th>ملاحظات</th>
            </tr>
          </thead>
          <tbody>
            ${itemsRows || '<tr><td colspan="5">لا توجد بنود</td></tr>'}
          </tbody>
        </table>
      </div>

      <div class="footer">Generated by JRD System</div>
    </div>
  `;
}

export default function Archive() {
  const [inventories, setInventories] = useState([]);
  const [total, setTotal] = useState(0);
  const [expanded, setExpanded] = useState(null);
  const [expandedData, setExpandedData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ from: '', to: '' });
  const [exportingId, setExportingId] = useState(null);

  const load = async () => {
    setLoading(true);
    try {
      const params = {};
      if (filters.from) params.from = filters.from;
      if (filters.to) params.to = filters.to;
      const res = await api.get('/inventory', { params });
      setInventories(res.data.inventories);
      setTotal(res.data.total);
    } catch {
      toast.error('خطأ في تحميل الأرشيف');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const toggleExpand = async (id) => {
    if (expanded === id) {
      setExpanded(null);
      setExpandedData(null);
      return;
    }
    try {
      const res = await api.get(`/inventory/${id}`);
      setExpandedData(res.data);
      setExpanded(id);
    } catch {
      toast.error('خطأ في تحميل التفاصيل');
    }
  };

  const deleteInventory = async (id) => {
    if (!confirm('هل تريد حذف هذا الجرد؟')) return;
    try {
      await api.delete(`/inventory/${id}`);
      toast.success('تم الحذف');
      load();
    } catch {
      toast.error('خطأ في الحذف');
    }
  };

  const exportInventoryPdf = async (id) => {
    setExportingId(id);
    let wrapper = null;
    try {
      const res = await api.get(`/inventory/${id}`);
      const inventory = res.data;

      wrapper = document.createElement('div');
      wrapper.style.position = 'fixed';
      wrapper.style.left = '-10000px';
      wrapper.style.top = '0';
      wrapper.style.width = '1120px';
      wrapper.style.padding = '16px';
      wrapper.style.background = '#f8fafc';
      wrapper.innerHTML = buildInventoryReportHtml(inventory);
      document.body.appendChild(wrapper);

      const canvas = await html2canvas(wrapper, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#f8fafc',
        logging: false,
      });

      const imageData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imageWidth = pageWidth;
      const imageHeight = (canvas.height * imageWidth) / canvas.width;

      let heightLeft = imageHeight;
      let position = 0;

      pdf.addImage(imageData, 'PNG', 0, position, imageWidth, imageHeight, '', 'FAST');
      heightLeft -= pageHeight;

      while (heightLeft > 0) {
        position = heightLeft - imageHeight;
        pdf.addPage();
        pdf.addImage(imageData, 'PNG', 0, position, imageWidth, imageHeight, '', 'FAST');
        heightLeft -= pageHeight;
      }

      pdf.save(`JRD_Inventory_${inventory.date}.pdf`);
      toast.success('تم تصدير ملف PDF');
    } catch {
      toast.error('تعذر تصدير PDF');
    } finally {
      if (wrapper && wrapper.parentNode) {
        wrapper.parentNode.removeChild(wrapper);
      }
      setExportingId(null);
    }
  };

  return (
    <div className="animate-fade-in max-w-5xl mx-auto">
      <h2 className="text-3xl font-bold text-gray-800 mb-6">الأرشيف</h2>

      {/* Filters */}
      <div className="bg-white rounded-xl shadow-lg p-4 mb-6">
        <div className="flex items-center gap-4 flex-wrap">
          <Filter size={18} className="text-gray-400" />
          <div className="flex items-center gap-2">
            <label className="text-sm text-gray-600">من:</label>
            <input
              type="date"
              value={filters.from}
              onChange={(e) => setFilters({ ...filters, from: e.target.value })}
              className="border border-gray-300 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-400"
            />
          </div>
          <div className="flex items-center gap-2">
            <label className="text-sm text-gray-600">إلى:</label>
            <input
              type="date"
              value={filters.to}
              onChange={(e) => setFilters({ ...filters, to: e.target.value })}
              className="border border-gray-300 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-400"
            />
          </div>
          <button onClick={load} className="bg-emerald-600 text-white px-4 py-1.5 rounded-lg text-sm hover:bg-emerald-700 transition-colors">
            بحث
          </button>
          <button
            onClick={() => { setFilters({ from: '', to: '' }); setTimeout(load, 0); }}
            className="text-gray-500 hover:text-gray-700 text-sm"
          >
            مسح الفلتر
          </button>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-20 text-gray-400">جاري التحميل...</div>
      ) : inventories.length === 0 ? (
        <div className="text-center py-20 text-gray-400">
          <Calendar size={48} className="mx-auto mb-4" />
          <p>لا يوجد جرد محفوظ بعد</p>
        </div>
      ) : (
        <div className="space-y-3">
          {inventories.map((inv) => (
            <div key={inv.id} className="bg-white rounded-xl shadow-lg overflow-hidden">
              <div
                className="flex items-center justify-between p-4 cursor-pointer hover:bg-gray-50 transition-colors"
                onClick={() => toggleExpand(inv.id)}
              >
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 bg-emerald-100 rounded-full flex items-center justify-center">
                    <Calendar size={18} className="text-emerald-600" />
                  </div>
                  <div>
                    <p className="font-bold">{inv.date}</p>
                    <p className="text-sm text-gray-500">سعر الصرف: {inv.exchange_rate}</p>
                  </div>
                </div>

                <div className="flex items-center gap-6">
                  <div className="text-left">
                    <p className="text-sm text-gray-500">المجموع</p>
                    <p className="font-bold text-emerald-700">${Number(inv.total_converted_usd).toFixed(2)}</p>
                  </div>
                  <div className="text-left">
                    <p className="text-sm text-gray-500">الربح</p>
                    <p className={`font-bold ${inv.profit >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                      ${Number(inv.profit).toFixed(2)}
                    </p>
                  </div>
                  <button
                    onClick={(e) => { e.stopPropagation(); exportInventoryPdf(inv.id); }}
                    disabled={exportingId === inv.id}
                    className="p-2 text-blue-500 hover:text-blue-700 hover:bg-blue-50 rounded-lg disabled:opacity-50"
                    title="تصدير PDF"
                  >
                    <FileDown size={16} className={exportingId === inv.id ? 'animate-pulse' : ''} />
                  </button>
                  <button
                    onClick={(e) => { e.stopPropagation(); deleteInventory(inv.id); }}
                    className="p-2 text-red-400 hover:text-red-600 hover:bg-red-50 rounded-lg"
                  >
                    <Trash2 size={16} />
                  </button>
                  {expanded === inv.id ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                </div>
              </div>

              {expanded === inv.id && expandedData && (
                <div className="border-t p-4 bg-gray-50">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="text-gray-500">
                        <th className="text-right py-1 px-2">الاسم</th>
                        <th className="text-center py-1 px-2">الليرة ₺</th>
                        <th className="text-center py-1 px-2">الدولار $</th>
                        <th className="text-center py-1 px-2">ملاحظات</th>
                      </tr>
                    </thead>
                    <tbody>
                      {expandedData.items?.map((item, i) => (
                        <tr key={i} className="border-t border-gray-200">
                          <td className="py-1 px-2">{item.item_name}</td>
                          <td className="text-center py-1 px-2">{Number(item.try_amount).toLocaleString()}</td>
                          <td className="text-center py-1 px-2">{Number(item.usd_amount).toLocaleString()}</td>
                          <td className="text-center py-1 px-2 text-gray-400">{item.notes}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
